<?php

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_farm_entity_bundle_field_info().
 */
function farm_equipment_asset_extended_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle) {
  $fields = [];

  // Add a new fields to Equipment Assets. 'asset' specifies the entity type and
  // 'equipment' specifies the bundle.
  if ($entity_type->id() == 'asset' && $bundle == 'equipment') {
    // Options for the new field. See Field options below.
    $options = [
      'type' => 'entity_reference',
      'label' => t('Equipment type'),
      'description' => t('Enter the type of equipment.'),
      'target_type' => 'taxonomy_term',
      'target_bundle' => 'equipment_type',
      'auto_create' => TRUE,
      'required' => TRUE,
      'weight' => [
        'form' => 10,
        'view' => 10,
      ],
    ];
    $fields['equipment_type'] = \Drupal::service('farm_field.factory')->bundleFieldDefinition($options);
  }
  return $fields;
}
